# Generated by Django 6.0.1 on 2026-01-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hiring_radius_miles',
            field=models.IntegerField(default=50, help_text='Hiring radius in miles'),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
