# Generated by Django 6.0.1 on 2026-02-01 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_options_job_benefits_job_bonuses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name (e.g., Swift Transportation)', max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='carrier_logos/')),
                ('description', models.TextField(blank=True, help_text='Company overview/description', null=True)),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=20, null=True)),
                ('benefit_401k', models.TextField(blank=True, help_text='401(k) retirement plan details', null=True)),
                ('benefit_disability_life', models.TextField(blank=True, help_text='Disability, life, accident & critical illness coverage', null=True)),
                ('benefit_stock_purchase', models.TextField(blank=True, help_text='Stock purchase program details', null=True)),
                ('benefit_medical_dental_vision', models.TextField(blank=True, help_text='Medical, dental & vision plans', null=True)),
                ('benefit_paid_vacation', models.TextField(blank=True, help_text='Paid vacation policy', null=True)),
                ('benefit_prescription_drug', models.TextField(blank=True, help_text='Prescription drug plans', null=True)),
                ('benefit_weekly_paycheck', models.TextField(blank=True, help_text='Weekly paycheck information', null=True)),
                ('benefit_driver_ranking_bonus', models.TextField(blank=True, help_text='Driver ranking bonus details', null=True)),
                ('benefit_military_program', models.TextField(blank=True, help_text='Military benefits program', null=True)),
                ('benefit_tuition_program', models.TextField(blank=True, help_text='Debt-free tuition program details', null=True)),
                ('benefit_other', models.TextField(blank=True, help_text='Any other benefits', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this carrier is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='job',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this job is active/visible'),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, help_text='Application URL', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Job-specific contact information', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Job description, lane information, routes, etc.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='driver_type',
            field=models.CharField(blank=True, help_text='Company Driver, Owner Operator', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='equipment_type',
            field=models.CharField(blank=True, help_text='Dry Van, Reefer, Flatbed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, help_text='0, 3, 6, 12 months', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='freight_type',
            field=models.CharField(blank=True, help_text='No Touch, Driver Unload', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='home_time',
            field=models.CharField(blank=True, help_text='Daily, Weekly, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(help_text='Job location', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay_type',
            field=models.CharField(blank=True, help_text='Weekly, Hourly, Per Mile, etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, help_text='Specific job requirements', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, help_text='Pay information', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule_type',
            field=models.CharField(blank=True, help_text='Schedule details', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='states_covered',
            field=models.CharField(blank=True, help_text='Comma-separated state codes', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text='Job title/position', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='zip_code',
            field=models.CharField(help_text='Location zip code', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='carrier',
            field=models.ForeignKey(default=1, help_text='The carrier/company posting this job', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.carrier'),
            preserve_default=False,
        ),
    ]
