# Generated by Django 6.0.1 on 2026-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_carrier_alter_job_options_remove_job_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='account_recruiting_status',
            field=models.CharField(blank=True, help_text='OPEN, CLOSED, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cost_center',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='driver_leader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='leadership_approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='line_of_business',
            field=models.CharField(blank=True, help_text='DED-WAL GRO, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='must_live_within',
            field=models.CharField(blank=True, help_text='Distance requirement', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='no_hire_cities',
            field=models.TextField(blank=True, help_text='Cities to avoid hiring from', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ok_to_hire_cities',
            field=models.TextField(blank=True, help_text='Cities approved for hiring', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='onsite_manager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='onsite_manager_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='owner_operators_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='regional_leader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='regional_leader_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source_create_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source_modified_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='teams_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='total_drivers_needed_solo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='total_drivers_needed_team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='trainees_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
