# Generated by Django 6.0.1 on 2026-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_account_recruiting_status_job_cost_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='job',
            name='driver_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='equipment_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='freight_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='states_covered',
        ),
        migrations.AddField(
            model_name='job',
            name='account_type',
            field=models.CharField(blank=True, help_text='Account types (comma-separated): Dedicated, OTR, Regional, Local', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cameras',
            field=models.CharField(blank=True, help_text='Camera types (comma-separated): Inward Facing, Outward Facing, Both, None', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='driver_types',
            field=models.CharField(blank=True, help_text='Driver types (comma-separated): Company Driver, Owner Operator, Lease Purchase', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='drug_test_type',
            field=models.CharField(blank=True, help_text='Drug test types (comma-separated): Hair Follicle, Urinalysis, Both', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_levels',
            field=models.CharField(blank=True, help_text='Experience levels (comma-separated): 0 months, 3 months, 6 months, 12 months, 24 months', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='freight_types',
            field=models.CharField(blank=True, help_text='Freight types (comma-separated): Dry Van, Reefer, Flatbed, Tanker, Intermodal, etc.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sap_required',
            field=models.CharField(blank=True, help_text='SAP requirement (comma-separated): Yes, No, Conditional', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='states',
            field=models.CharField(blank=True, help_text='States covered (comma-separated state codes): AL, AK, AZ, etc.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='transmissions',
            field=models.CharField(blank=True, help_text='Transmission types (comma-separated): Automatic, Manual, Both', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='trainees_accepted',
            field=models.CharField(blank=True, help_text='Trainee acceptance options (comma-separated): Yes, No, Conditional', max_length=200, null=True),
        ),
    ]
