# Generated by Django 6.0.1 on 2026-02-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_apply_link_remove_job_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='headquarters_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='headquarters_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='headquarters_zip',
            field=models.CharField(blank=True, help_text='Headquarters zip code (used as fallback for jobs without specific location)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='zip_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manually Entered'), ('extracted', 'Extracted from Description'), ('geocoded', 'Auto-Geocoded from Location'), ('carrier_hq', 'Carrier Headquarters'), ('state_capital', 'State Capital Default')], help_text='Source of zip code data', max_length=20, null=True),
        ),
    ]
