# Generated by Django 6.0.1 on 2026-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_carrier_headquarters_city_carrier_headquarters_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='average_weekly_pay',
            field=models.CharField(blank=True, help_text='Average weekly pay', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='bonus_offer',
            field=models.CharField(blank=True, help_text='Bonus offers', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='exact_home_time',
            field=models.CharField(blank=True, help_text='Specific home time details', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='load_unload_type',
            field=models.CharField(blank=True, help_text='Live Load, Drop and Hook, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_duration',
            field=models.CharField(blank=True, help_text="Duration of orientation (e.g., '3-5 days')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_location',
            field=models.CharField(blank=True, help_text='Orientation location (city, state)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_lodging',
            field=models.CharField(blank=True, help_text='Lodging arrangements during orientation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_meals',
            field=models.CharField(blank=True, help_text='Meal arrangements during orientation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_notes',
            field=models.TextField(blank=True, help_text='Additional orientation details (can include table data)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_pay',
            field=models.CharField(blank=True, help_text='Orientation pay details', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_transportation',
            field=models.CharField(blank=True, help_text='Transportation to/from orientation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_range',
            field=models.CharField(blank=True, help_text='Pay range (e.g., $0.43-$0.51 CPM)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='short_haul_pay',
            field=models.CharField(blank=True, help_text='Pay for short hauls', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stop_pay',
            field=models.CharField(blank=True, help_text='Pay per stop', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='unload_pay',
            field=models.CharField(blank=True, help_text='Pay for unloading', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='home_time',
            field=models.CharField(blank=True, help_text='General home time (Daily, Weekly, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, help_text='General pay information', max_length=100, null=True),
        ),
    ]
