# Generated by Django 6.0.1 on 2026-02-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_average_weekly_pay_job_bonus_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='account_recruiting_status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='job',
            name='driver_leader',
        ),
        migrations.RemoveField(
            model_name='job',
            name='leadership_approval_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='line_of_business',
        ),
        migrations.RemoveField(
            model_name='job',
            name='must_live_within',
        ),
        migrations.RemoveField(
            model_name='job',
            name='no_hire_cities',
        ),
        migrations.RemoveField(
            model_name='job',
            name='ok_to_hire_cities',
        ),
        migrations.RemoveField(
            model_name='job',
            name='onsite_manager',
        ),
        migrations.RemoveField(
            model_name='job',
            name='onsite_manager_contact',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_duration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_lodging',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_meals',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_notes',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_pay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_transportation',
        ),
        migrations.RemoveField(
            model_name='job',
            name='owner_operators_accepted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='regional_leader',
        ),
        migrations.RemoveField(
            model_name='job',
            name='regional_leader_contact',
        ),
        migrations.RemoveField(
            model_name='job',
            name='teams_accepted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='total_drivers_needed_solo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='total_drivers_needed_team',
        ),
        migrations.AddField(
            model_name='job',
            name='account_overview',
            field=models.TextField(blank=True, help_text='Paste all account overview information here', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='administrative_details',
            field=models.TextField(blank=True, help_text='Paste all administrative details here (managers, contacts, cost center, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_details',
            field=models.TextField(blank=True, help_text='Paste all job details here (routes, schedule, equipment, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_details',
            field=models.TextField(blank=True, help_text='Paste all orientation details here (location, duration, pay, lodging, meals, transportation)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation_table',
            field=models.TextField(blank=True, help_text='Optional: Paste orientation table data here', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='General job description and lane information', null=True),
        ),
    ]
