# Generated by Django 6.0.1 on 2026-02-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_job_account_recruiting_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='', help_text='Primary state for the job', max_length=200),
            preserve_default=False,
        ),
    ]
