# Generated by Django 6.0.1 on 2026-02-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_location_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_source',
            field=models.CharField(blank=True, choices=[('job_zip', 'Job ZIP Code'), ('carrier_hq', 'Carrier Headquarters'), ('state_only', 'State Level Only')], help_text='Source of location data for transparency', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Auto-populated from ZIP code or carrier HQ', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Auto-populated from ZIP code or carrier HQ', max_digits=9, null=True),
        ),
    ]
