# Generated by Django 6.0.1 on 2026-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_location_source_alter_job_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='app_process',
            field=models.TextField(blank=True, help_text='Application process instructions', null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='pre_qualifications',
            field=models.TextField(blank=True, help_text='Pre-qualification requirements (paste table data here)', null=True),
        ),
        migrations.AddField(
            model_name='carrier',
            name='presentation',
            field=models.TextField(blank=True, help_text='Carrier presentation details (paste table data here)', null=True),
        ),
    ]
