# Generated by Django 6.0.1 on 2026-02-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_carrier_app_process_carrier_pre_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avg_weekly_miles',
            field=models.CharField(blank=True, help_text='Average weekly miles', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='equipment_bunks',
            field=models.CharField(blank=True, help_text='Number of bunks or bunk configuration', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='equipment_engine',
            field=models.CharField(blank=True, help_text='Engine type/specs', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='key_disqualifiers',
            field=models.TextField(blank=True, help_text='Key disqualifiers for this job', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='no_touch_freight',
            field=models.CharField(blank=True, help_text='No Touch Freight (e.g. Yes, No, 70%)', max_length=100, null=True),
        ),
    ]
