# Generated by Django 6.0.1 on 2026-02-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_avg_weekly_miles_job_equipment_bunks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='account_overview',
        ),
        migrations.RemoveField(
            model_name='job',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='administrative_details',
        ),
        migrations.RemoveField(
            model_name='job',
            name='average_weekly_pay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='avg_weekly_miles',
        ),
        migrations.RemoveField(
            model_name='job',
            name='bonus_offer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cameras',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='driver_types',
        ),
        migrations.RemoveField(
            model_name='job',
            name='drug_test_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='equipment_bunks',
        ),
        migrations.RemoveField(
            model_name='job',
            name='equipment_engine',
        ),
        migrations.RemoveField(
            model_name='job',
            name='exact_home_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_levels',
        ),
        migrations.RemoveField(
            model_name='job',
            name='freight_types',
        ),
        migrations.RemoveField(
            model_name='job',
            name='home_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_details',
        ),
        migrations.RemoveField(
            model_name='job',
            name='load_unload_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='no_touch_freight',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_details',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orientation_table',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pay_range',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sap_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='short_haul_pay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='states',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stop_pay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='trainees_accepted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='transmissions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='unload_pay',
        ),
        migrations.AddField(
            model_name='job',
            name='equipment_details',
            field=models.TextField(blank=True, help_text='Paste all equipment-related details here.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, help_text='Paste all job description details, account overview, and highlights here.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_details',
            field=models.TextField(blank=True, help_text='Paste all pay details, bonuses, and compensation info here.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_details',
            field=models.TextField(blank=True, help_text='Paste all job requirements and qualification details here.', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='key_disqualifiers',
            field=models.TextField(blank=True, help_text='Key disqualifiers for this job.', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='zip_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
