# Generated by Django 6.0.1 on 2026-02-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_remove_job_account_overview_remove_job_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='job_details',
        ),
    ]
