# Generated by Django 6.0.1 on 2026-02-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_rename_job_description_job_job_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hiring_status',
            field=models.CharField(choices=[('open', 'Open to hiring'), ('full', 'Marked as full')], default='open', help_text='Current hiring status of the job', max_length=10),
        ),
    ]
