# Generated by Django 6.0.1 on 2026-02-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_hiring_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, null=True)),
                ('state', models.CharField(help_text='State (e.g., TX or Texas)', max_length=100)),
                ('zip_code', models.CharField(help_text='Zip code for this location', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(help_text='The job this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='additional_locations', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Additional Location',
                'verbose_name_plural': 'Additional Locations',
            },
        ),
    ]
