# Generated by Django 6.0.1 on 2026-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_joblocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='multi_zip_codes',
            field=models.TextField(blank=True, help_text="Paste multiple locations here. Format: '25401 (Martinsburg), 07001 (Avenel)'. States will be auto-detected.", null=True),
        ),
    ]
