# Generated by Django 6.0.1 on 2026-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_job_multi_zip_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='average_weekly_pay',
            field=models.CharField(blank=True, help_text='e.g., $1,500 - $2,000', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='driver_type',
            field=models.CharField(blank=True, help_text='e.g., Regional, OTR, Local', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, help_text='e.g., 12 months', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='freight_type',
            field=models.CharField(blank=True, help_text='e.g., Dry Van, Reefer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='home_time',
            field=models.CharField(blank=True, help_text='e.g., Weekly, Bi-Weekly', max_length=100, null=True),
        ),
    ]
