# Generated by Django 6.0.1 on 2026-02-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_job_average_weekly_pay_job_driver_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='average_weekly_pay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='driver_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='freight_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='home_time',
        ),
    ]
