# Generated by Django 6.0.1 on 2026-02-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_remove_job_average_weekly_pay_remove_job_driver_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, help_text='Primary state for the job', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Location zip code', max_length=10, null=True),
        ),
    ]
