# Generated by Django 6.0.1 on 2026-02-22 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_alter_job_state_alter_job_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Academy name (e.g., Swift Academy - Phoenix)', max_length=200)),
                ('city', models.CharField(blank=True, help_text='City where academy is located', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State abbreviation', max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='Academy zip code', max_length=10, null=True)),
                ('training_type', models.CharField(blank=True, help_text='Type of training: In-Person, Streaming/Virtual, ELDT Only, etc.', max_length=50, null=True)),
                ('program_length_days', models.IntegerField(blank=True, help_text='Approximate length of the academy program in days', null=True)),
                ('tuition_cost', models.CharField(blank=True, help_text="Tuition cost for the program (e.g., '$1,995')", max_length=100, null=True)),
                ('tuition_notes', models.TextField(blank=True, help_text='Notes on tuition financing, debt-free program, payback terms, etc.', null=True)),
                ('trainee_pay', models.CharField(blank=True, help_text="Pay rate while in training (e.g., '$300/week' or 'Unpaid')", max_length=200, null=True)),
                ('orientation_pay', models.CharField(blank=True, help_text="Pay once officially hired for orientation (e.g., '$300 paid if officially hired')", max_length=200, null=True)),
                ('requirements', models.TextField(blank=True, help_text='Requirements to enroll (age, background check, medical, etc.)', null=True)),
                ('academy_details', models.TextField(blank=True, help_text='General academy info, schedule, what to expect, orientations, etc.', null=True)),
                ('after_graduation', models.TextField(blank=True, help_text='What happens after graduating - fleet placement, contract requirements, etc.', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(help_text='The carrier sponsoring this academy', on_delete=django.db.models.deletion.CASCADE, related_name='academies', to='jobs.carrier')),
            ],
            options={
                'verbose_name': 'Academy',
                'verbose_name_plural': 'Academies',
                'ordering': ['carrier', 'state', 'city'],
            },
        ),
    ]
