# Generated by Django 6.0.3 on 2026-03-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_add_academy_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='benefits',
            field=models.TextField(blank=True, help_text='Consolidated benefits (paste table data here)', null=True),
        ),
    ]
